### ISSUE TITLE
Error while running submitPT and submitFT   FileNotFoundError: [Errno 2] No such file or directory 

### ISSUE THREAD

**Issue by pramodkp** [olsson-group/RL-GraphINVENT#3]
Hi,

Error when running submitPT.py

(RL-GraphINVENT-env) user@Pramod:~$ python submitPT.py
* Creating dataset directory output_chembl25_500k/train/
* Creating model subdirectory output_chembl25_500k/train/job_0/
* Running job as a normal process.
/home/anaconda3/envs/RL-GraphINVENT-env/bin/python
* Running job using HDF datasets located at data/pre-training/chembl25_500k/
* Checking that the relevant parameters match those used in preprocessing the dataset.
Traceback (most recent call last):
  File "pre-training/main.py", line 5, in <module>
    import util
  File "/home/RL-GraphINVENT/pre-training/util.py", line 6, in <module>
    from tensorboard_writer import writer as tb_writer
  File "/home/RL-GraphINVENT/pre-training/tensorboard_writer.py", line 5, in <module>
    from parameters.constants import constants as C
  File "/home/RL-GraphINVENT/pre-training/parameters/constants.py", line 255, in <module>
    job_dir=args.job_dir)
  File "/home/RL-GraphINVENT/pre-training/parameters/constants.py", line 235, in collect_global_constants
    params_to_check = load_params(input_csv_path=csv_file)
  File "/home/cadd/RL-GraphINVENT/pre-training/parameters/constants.py", line 104, in load_params
    with open(input_csv_path, "r") as csv_file:
FileNotFoundError: [Errno 2] No such file or directory: 'data/pre-training/chembl25_500k/preprocessing_params.csv'
-- Sleeping 2 seconds.

Error when running submitFT.py
(RL-GraphINVENT-env) user@Pramod:~$ python submitFT.py
* Creating dataset directory output_chembl25_500k/score_name/
* Creating model subdirectory output_chembl25_500k/score_name/job_0/
* Running job as a normal process.
/home/anaconda3/envs/RL-GraphINVENT-env/bin/python
* Running job using HDF datasets located at data/fine-tuning/chembl25_500k/
* Checking that the relevant parameters match those used in preprocessing the dataset.
-- Job parameters match preprocessing parameters.
* Run mode: 'generate'
* Loading training set properties.
* Loading model from previous saved state (Epoch 5).
Traceback (most recent call last):
  File "fine-tuning/main.py", line 54, in <module>
    main()
  File "fine-tuning/main.py", line 40, in main
    workflow.generation_phase()
  File "/home/RL-GraphINVENT/fine-tuning/Workflow.py", line 183, in generation_phase
    self.agent_model = torch.load(model_path)
  File "/home/anaconda3/envs/RL-GraphINVENT-env/lib/python3.6/site-packages/torch/serialization.py", line 419, in load
    f = open(f, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'output_chembl25_500k/score_name/job_0/model_restart_5.pth'
-- Sleeping 2 seconds.

**Comment by 688spiderbin** [comment]
I have encountered the same issues

**Comment by DylanMing** [comment]
same issues，
In `submitPT.py`, I used `preprocessing_params.csv` in `data/fine-tuning/output_chembl25_500k`, it can continue run for the problem of `preprocessing_params.csv`, but it also has problem with the files,
- FileNotFoundError: [Errno 2] Unable to synchronously open file (unable to open file: name = 'data/pre-training/chembl25_500k/valid.h5', errno = 2, error message = 'No such file or directory', flags = 1, o_flags = 2)

I think there may be some prepocess program need to be excute before the pre-train.

`submitFT.py` is the same, it maybe need pre-train to generate the  `model_restart_5.pth`
